### ISSUE TITLE
fix: hst264 redirect not working

### ISSUE THREAD

**Issue by Peace-Makers** [elementaryrock/jiocinema4k#1]
Now getting error 404 Not Found

**Comment by Peace-Makers** [comment]
ok found the issue 
jc_web_premium -> jc_androidtv_premium , this redirect is working (checked Asur series)
but hst264_web_premium -> jc_androidtv_premium was giving 404 (checked Minions: The Rise of Gru)

so, I did same rewrite for hst264 and now it works, replace web with android thats it.
hst264_web_premium -> hst264_androidtv_premium


Please update the image to this
<img width="952" alt="image" src="https://github.com/user-attachments/assets/c276289a-2857-42ff-9a7d-3273b4ac5018">

**Comment by elementaryrock** [comment]
Thanks for informing me about the updated redirect for hst264_web_premium. I've updated the image accordingly.
